sudo: false
language: java
addons:
  apt:
    packages:
    - oracle-java8-installer
script: "
  ./gradlew ci
"
jdk:
- oraclejdk8
env:
  global:
  - CI: true
  - secure: AQCTfYqfWjHp+ePQ+8Jb7Z6d2bqB/Il6Isnf8Vh0NqIZjK7+jrVA8qLsSADKH7SSIyNcJA3PA+O5d5rkejqweKi5j7KhXWQD0QJxP2DkLwX9J2/A3HmhjBSqhi2IKra4p9HG2xV9fct+CtmL8SOozYFOW/C1ILQHtqNKB0W4GIGy+Gf1E+HB6ktNLnMsdLUEJ9d575Uq7hzS/Q83RfgAYtjusOy/yeXwZogiGrItAmUIMX4b61JlHJxfDL8dkAjzlxfnrXYlB7nMmjWZIEZjyloGeyDfYM8pIaebAq4JpTHPWpUfe5lz1LvPvDfeVpuKMlbWby/1ZyB+NA2hK524Kp+kfYdaNcCj1IPS0bEkXW7qlDuTpbg6uZNcVH7jWkas/EEz3MB9z+9/3KhK3xjZPh/8l5ZloO/F4dTiIyQdlosUHfXYyjR4qAoaWhR/KMhQ12SlgRQcoCWk98aQ2821Sr7Lx6lByEsXPPjFDBQY84Uw5B4Dp6Wv1kfez3TRTmncEZN6Pa7J4g1y5yd1qILs/K8FpXlNuR1mfKfWltDihDx4XB7dGaPFE9ZHvX7ceZFi2cgHgKRowBJXzAFJRcneV5XDPde1jtAQ9LD0RYGGHHM4XQHvKbXqzj5tST/8i1GLvz8uy8lp3f8XQj8i/etIe4LO8FXjWaJSD7t/XrxLRNU=
  - secure: w55k9saRM4vYlrvOGzlNrlh/q3WJur54CF7yU5ahUFOskqwaABLo9pWhWXQQgmZ1qKpgXNf13OFOuTSVbzAalncZ9f59qlJkz9veMEuBIWB24iMH/xrXKJMjCwa1BBFJJ3L8xg6DPh4IHvHBto2XoftsiM6K/Y4Ttu7sA804Cw2f4JghDAAEEbLvjC13pswJXZCSlIfVA80uA97ZRwrdrIPmjBtr8Uqtg/qBRickiLIffXVLlXozAxCbwrRqa1moaWeEoMSmCQkJBPi6mxaphEoo2yF/bYPbL12HwzG+GyRuWqlVi9r0ZHRBeLXNXqaOAdNqsta5Ox69EcmB2UrmFCq27WcHaWL8b5Y1AQ3FhUPtoPWkXENfJvBF8H46mOiU13jvgawSUDxd+bH7nR841/esXPygn0AcJVjkRdzi3ruq1wr4myqvUQUJ231PeGYQKJyA0u1wuvXhKlyCj/8UUOQUMhDm9kOZLP+L5mPANSqoLmzx/TUR4AKx9FsfKZvyZqQaxD48e7+cQBTMF7t+V+arDHbAgirnIZIV8LU3vD4CpJklKEQiN7z5sqFAPXYr8Bs+iRxQWPOLDQ5ouYUQH9a7TjDwe8YGz7hRq/GvxcJBkM2AjEV4HxmL1Nc2tYp9n41WhrWFQdtXzYsMi2o1fvmgnl7z5e4lPRTFcricEw8=
